export const posts = [
  {
    id: 1,
    titulo: "Desondulação: O Segredo para o Caimento Perfeito",
    resumo: "Cansado do volume excessivo e dos fios rebeldes? A desondulação relaxa a estrutura do cabelo, facilitando o penteado no dia a dia sem perder a naturalidade.",
    categoria: "Química & Tratamento",
    imagem: "/cortes/corte21.png",
    data: "12 Jun, 2026",
    destaque: true,
  },
  {
    id: 2,
    titulo: "Mid, Low ou High Fade: Qual degradê combina com você?",
    resumo: "Entenda a diferença entre as alturas do degradê e descubra qual técnica valoriza mais o formato do seu rosto.",
    categoria: "Tendências",
    imagem: "/cortes/corte4.jpg",
    data: "05 Jun, 2026",
    destaque: false,
  },
  {
    id: 3,
    titulo: "Barba de Respeito: 3 passos diários essenciais",
    resumo: "Ter uma barba cheia e alinhada não é só genética. Veja a rotina de 3 minutos que muda o aspecto dos fios.",
    categoria: "Cuidados",
    imagem: "/cortes/Barba.png",
    data: "28 Mai, 2026",
    destaque: false,
  },
  {
    id: 4,
    titulo: "Corte na Tesoura: O Clássico que nunca morre",
    resumo: "Para quem tem cabelo mais longo ou ondulado, a tesoura entrega um caimento que a máquina não consegue.",
    categoria: "Clássicos",
    imagem: "/cortes/corte12.jpeg",
    data: "15 Mai, 2026",
    destaque: false,
  },
  {
    id: 6,
    titulo: "Mullet Moderno: A volta do estilo com atitude",
    resumo: "O Mullet voltou com tudo, misturado com o fade lateral. Veja como aderir a essa tendência sem errar.",
    categoria: "Tendências",
    imagem: "/cortes/corte8.png",
    data: "02 Mai, 2026",
    destaque: false,
  },
  {
    id: 7,
    titulo: "Estilo Desde Cedo: A experiência do Corte Infantil",
    resumo: "Cortar o cabelo dos pequenos exige paciência e técnica. Veja como transformamos o choro em um momento de diversão e muito estilo.",
    categoria: "Kids",
    imagem: "/cortes/corte1.jpg",
    data: "25 Abr, 2026",
    destaque: false,
  },
  {
    id: 9,
    titulo: "Freestyle & Design: Arte na lateral do cabelo",
    resumo: "Linhas, traços e desenhos que mostram personalidade. Como escolher o freestyle ideal para o seu formato de corte.",
    categoria: "Arte Urbana",
    imagem: "/cortes/corte14.jpeg",
    data: "10 Abr, 2026",
    destaque: false,
  },
];
